#!/usr/bin/env bash
# One-time macOS setup. Copy this folder to the Mac and run: ./install-macos.sh
set -euo pipefail
cd "$(dirname "$0")"
brew list hidapi >/dev/null 2>&1 || brew install hidapi
brew list --cask hammerspoon >/dev/null 2>&1 || brew install --cask hammerspoon
# Hammerspoon runs with a minimal PATH, so pin the python3 that gets the hid package.
PYTHON="$(command -v python3)"
"$PYTHON" -m pip install --user --break-system-packages hid 2>/dev/null || "$PYTHON" -m pip install --user hid
mkdir -p ~/.hammerspoon
SCRIPT="$(pwd)/switch-hosts.py"

# Drop the Cmd+Alt+S hotkey written by earlier versions of this script.
if [ -f ~/.hammerspoon/init.lua ]; then
  perl -0pi -e 's/\n-- Logitech: send mouse \+ keyboard to the Ubuntu slot \(2\)\. Cmd\+Alt\+S\.\nhs\.hotkey\.bind\(.*?\nend\)\n//s' ~/.hammerspoon/init.lua
fi

cat > ~/.hammerspoon/logi_switch.lua <<LUA
-- Generated by logi-switch/install-macos.sh.
-- Rest the pointer in the bottom-left corner of a screen to send the Logitech
-- mouse + keyboard to Ubuntu (Easy-Switch slot 2).
local PYTHON, SCRIPT, SLOT = "$PYTHON", "$SCRIPT", "2"
local CORNER_PX, DWELL = 2, 0.4
local since, armed = nil, true

-- Kept global so the timer isn't garbage collected.
logiSwitchCornerTimer = hs.timer.doEvery(0.1, function()
  local screen = hs.mouse.getCurrentScreen()
  if not screen then return end
  local p, f = hs.mouse.absolutePosition(), screen:fullFrame()
  local inCorner = p.x <= f.x + CORNER_PX and p.y >= f.y + f.h - 1 - CORNER_PX
  if not inCorner then
    since, armed = nil, true
  elseif armed then
    local now = hs.timer.secondsSinceEpoch()
    if not since then
      since = now
    elseif now - since >= DWELL then
      -- The pointer stays parked here while the devices are away, so only
      -- re-arm once it has left the corner.
      armed = false
      hs.task.new(PYTHON, nil, {SCRIPT, SLOT}):start()
    end
  end
end)
LUA
grep -q 'require("logi_switch")' ~/.hammerspoon/init.lua 2>/dev/null \
  || printf '\nrequire("logi_switch")\n' >> ~/.hammerspoon/init.lua
echo "Done. Open Hammerspoon and reload its config."
echo "macOS may also ask to grant python3 Input Monitoring the first time."
